kind: source
spec:
  name: "aws-config"
  path: "cloudquery/aws"
  version: "v22.12.0"
  tables:
    - aws_config_config_rules
    - aws_config_config_rule_compliance_details
    - aws_config_config_rule_compliances
    - aws_config_remediation_configurations
  destinations: ["postgresql"]
  spec:
    regions: 
      - ap-southeast-2
    aws_debug: false
    org:
      admin_account:
        # make sure you have created local aws config, reference aws-config-<env> file
        local_profile: cloudquery
      member_role_name: cloudquery-ro
